Update SIP-12 types
MetaMask/SIPs pull request #107
Opened 2023-09-21 13:42 UTC by hmalik88

Previous args types were invalid, response type was updated to be more specific.

2023-09-21 16:40 UTC, Montoya requested changes

2023-09-21 16:40 UTC, Montoya commented on SIPS/sip-12.md
> +  | { resolvedDomain: string; resolvedAddress?: never }
Is this missing line breaks?

2023-09-21 16:43 UTC, hmalik88 commented on SIPS/sip-12.md
> +  | { resolvedDomain: string; resolvedAddress?: never }
I don't think so?

2023-09-21 21:12 UTC, Montoya commented on SIPS/sip-12.md
> +  | { resolvedDomain: string; resolvedAddress?: never }
OK cool

2023-09-21 21:15 UTC, Montoya approved these changes

2023-09-22 14:02 UTC, GuillaumeRx approved these changes

2023-09-22 14:06 UTC, Montoya approved these changes
LGTM

2023-09-22 14:08 UTC, merged