SIP-30: Entropy Source Identifiers
MetaMask/SIPs pull request #156
Opened 2024-12-17 15:14 UTC by shane-t

2024-12-18 16:09 UTC, Montoya commented
Why does this have to be a new API? If it involves a new optional parameter, it can be backwards compatible. If the Snap does not include the parameter in the request, default to the legacy behavior. If the parameter is included, then use that parameter to identify the entropy source.

2024-12-20 11:36 UTC, shane-t commented
> Why does this have to be a new API? If it involves a new optional parameter, it can be backwards compatible. If the Snap does not include the parameter in the request, default to the legacy behavior. If the parameter is included, then use that parameter to identify the entropy source.

That's the general idea. We retain all the `snap_get*Entropy` methods but include a new `source` parameter

2024-12-20 11:40 UTC, shane-t commented
@Montoya I've added a section describing the behaviour if the parameter is not included

2024-12-20 15:01 UTC, FrederikBolding commented on SIPS/sip-30.md
> +#### `snap_getBip32PublicKeyFromSource`
```suggestion
#### `snap_getBip32PublicKey`
```

2024-12-20 15:01 UTC, FrederikBolding commented on SIPS/sip-30.md
> +#### `snap_listAvailableEntropySources`
```suggestion
#### `snap_listEntropySources`
```

2025-01-06 15:21 UTC, FrederikBolding commented on SIPS/sip-30.md
> +If a snap is asked to create an account via `keyring.createAccount`, and the `entropySource` parameter is provided, and the snap requires entropy to create an account,the snap SHOULD request the entr
```suggestion
If a snap is asked to create an account via `keyring.createAccount`, and the `entropySource` parameter is provided, and the snap requires entropy to create an account, the snap SHOULD request the entropy from the specified source.
```

2025-01-06 15:22 UTC, FrederikBolding commented on SIPS/sip-30.md
> +The method returns an array of `EntropySource` objects, each representing an available entropy source. It is intended that the snap will display this list to the user.
```suggestion
The method returns an array of `EntropySource` objects, each representing an available entropy source. The Snap MAY choose to display this list to the user.
```

2025-01-06 15:22 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `version` - The number 2. Version `2` is the first version that allows specifying a source ID.
We don't need to increment the versioning number since the `source` parameter is optional and nothing else needs to change for the entropy derivation (except the source)

2025-01-06 15:24 UTC, FrederikBolding commented on SIPS/sip-30.md
> +### Client wallet implementation
"Client wallet" can probably just be "client" in this entire section

2025-01-06 15:25 UTC, FrederikBolding commented on SIPS/sip-30.md
> +If the request does not include the `source` parameter, the wallet MUST return entropy from the default source.
Maybe worth writing a section about the **primary** entropy source and how not passing the option will always fall back to that.

2025-01-06 15:26 UTC, FrederikBolding commented on SIPS/sip-30.md
> +interface EntropySource {
Should we flag to the Snap which one is the primary one?

2025-01-06 16:16 UTC, shane-t commented on SIPS/sip-30.md
> +    "snap_listAvailableEntropySources": {}
That makes sense - I was going by (from [here](https://docs.metamask.io/snaps/reference/snaps-api/))

> Snaps can communicate with and modify the functionality of MetaMask using the [Snaps API](https://docs.metamask.io/snaps/learn/about-snaps/apis/#snaps-api). To call each method (except the [interactive UI methods](https://docs.metamask.io/snaps/reference/snaps-api/#interactive-ui-methods)), you must first [request permission](https://docs.metamask.io/snaps/how-to/request-permissions/) in the Snap manifest file.

But I agree there's no need to create a separate permission, given that (excluding backward compatibility) you need one thing to do the other. I'm not quite sure how to specify that though, given that (as far as I can tell) a snap has to request `snap_getEntropy`, `snap_getBip44Entropy` and so on. I was thinking something like

> A snap which is endowed with the permission `snap_getEntropy`, `snap_getBip44Entropy` or `snap_getBip32Entropy` may call the `snap_listAvailableEntropySources` method.

2025-01-06 16:20 UTC, shane-t commented on SIPS/sip-30.md
> +#### `snap_getBip32PublicKeyFromSource`
Thanks, changed

2025-01-06 16:21 UTC, shane-t commented on SIPS/sip-30.md
> +#### `snap_listAvailableEntropySources`
👍

2025-01-06 16:22 UTC, shane-t commented on SIPS/sip-30.md
> +If the request does not include the `source` parameter, the wallet MUST return entropy from the default source.
Thanks, I've split up Client Implementation and referred more explicitly to this - also used Primary everywhere

2025-01-06 16:23 UTC, shane-t commented on SIPS/sip-30.md
> +interface EntropySource {
I have added a simple boolean flag here

2025-01-06 16:51 UTC, FrederikBolding commented on SIPS/sip-30.md
> +    "snap_listAvailableEntropySources": {}
Yeah, specifying it in the SIP like that makes sense to me!

2025-01-07 11:21 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `source` (optional) - The ID of the entropy source to use. If not specified, the default entropy source will be used.
```suggestion
- `source` (optional) - The ID of the entropy source to use. If not specified, the primary entropy source will be used.
```

2025-01-07 11:21 UTC, FrederikBolding commented on SIPS/sip-30.md
> +    version: 2,
```suggestion
    version: 1,
```

2025-01-07 11:24 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `curve`: The curve to use - `secp256k1` or `ed25519`.
```suggestion
- `curve`: The curve to use - `secp256k1`, `ed25519` or `ed25519Bip32`.
```

2025-01-07 11:24 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `source`: The ID of the entropy source to use.
```suggestion
- `source` (optional) - The ID of the entropy source to use. If not specified, the primary entropy source will be used.
```

2025-01-07 11:26 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `source`: The ID of the entropy source to use.
Can we standardize the format for these? E.g. mark as optional etc as done for `snap_getEntropy`

2025-01-07 11:26 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `source` (optional) - The ID of the entropy source to use. If not specified, the default entropy source will be used.
```suggestion
- `source` (optional) - The ID of the entropy source to use. If not specified, the primary entropy source will be used.
```

2025-01-07 11:28 UTC, FrederikBolding commented on SIPS/sip-30.md
> +The method returns an array of `EntropySource` objects, each representing an available entropy source. The Snap MAY choose to display this list to the user.
```suggestion
The method returns an array of `EntropySource` objects, each representing an available entropy source (including the primary source). The Snap MAY choose to display this list to the user.
```

2025-01-07 12:01 UTC, Mrtenz requested changes
Mostly nits. Actual contents look good to me.

2025-01-07 12:01 UTC, Mrtenz commented on SIPS/sip-30.md
> +##### Parameters
```suggestion
##### Parameters

```

2025-01-07 12:01 UTC, Mrtenz commented on SIPS/sip-30.md
> +#### Returns
```suggestion
#### Returns

```

2025-01-07 12:01 UTC, Mrtenz commented on SIPS/sip-30.md
> +##### Parameters
```suggestion
##### Parameters

```

2025-01-07 12:01 UTC, Mrtenz commented on SIPS/sip-30.md
> +##### Returns
```suggestion
##### Returns

```

2025-01-07 13:38 UTC, danroc commented on SIPS/sip-30.md
> +interface EntropySource {
Maybe:

```suggestion
export type EntropySource = {
```

2025-01-07 15:01 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `source` (optional) - The ID of the entropy source to use.
```suggestion
- `source` (optional) - The ID of the entropy source to use. If not specified, the primary entropy source will be used.
```

2025-01-07 15:01 UTC, FrederikBolding commented on SIPS/sip-30.md
> +- `source` (optional) - The ID of the entropy source to use.
```suggestion
- `source` (optional) - The ID of the entropy source to use. If not specified, the primary entropy source will be used.
```

2025-01-07 16:35 UTC, shane-t commented on SIPS/sip-30.md
> +#### Handling Entropy Requests
Fixed, thanks!

2025-01-07 18:48 UTC, FrederikBolding submitted a review, later dismissed

2025-01-09 12:22 UTC, FrederikBolding approved these changes

2025-01-09 17:41 UTC, Mrtenz commented on SIPS/sip-30.md
> +
There's one empty line too many here now 😅
```suggestion
```

2025-01-10 11:09 UTC, merged