Added snap.manifest.json specification
MetaMask/SIPs pull request #79
Opened 2022-11-07 22:02 UTC by ritave

2022-11-08 23:10 UTC, ritave commented
Note this SIP is instantly marked as Final since the specification is already in use

2022-11-10 02:02 UTC, rekmarks requested changes

2022-11-10 02:02 UTC, rekmarks commented on SIPS/sip-9.md
> +It additionally provides a JSON Schema for the manifest.
```suggestion
The goal of this SIP is to supersede [Snaps Publishing Specification v0.1](https://github.com/MetaMask/specifications/blob/c226cbaca1deb83d3e85941d06fc7534ff972336/snaps/publishing.md), and move Snaps specifications into one place - Snaps Improvement Proposals.
```

2022-11-10 02:02 UTC, rekmarks commented on SIPS/sip-9.md
> +> Such sections are considered non-normative.
```suggestion
> Indented sections like this are non-normative.
```

2022-11-11 02:04 UTC, rekmarks commented on SIPS/sip-4.md
> +    > For example, if the installed snap is `npm:my-snap@1.0.0` while the dapp requests `npm:my-snap@^2.0.0`, the wallet will try to get the newest version from [npm.js](https://npmjs.com) and will u
```suggestion
    > For example, if the installed snap is `npm:my-snap@1.0.0` while the dapp requests `npm:my-snap@^2.0.0`, the wallet will try to get the newest version from [npm](https://npmjs.com) and will update the snap a version that satisfies `^2.0.0`.
```

2022-11-11 02:04 UTC, rekmarks approved these changes
Nice!

2022-11-11 02:15 UTC, merged